export const BOXART_SRC_MAP: Record<string, string[]> = {
  'red-blue': ['red.png', 'green.png'],
  yellow: ['yellow.png'],
  'gold-silver': ['gold.webp', 'silver.webp'],
  crystal: ['crystal.png'],
  'ruby-sapphire': ['ruby.png', 'sapphire.png'],
  emerald: ['emerald.png'],
  'firered-leafgreen': ['fire_red.png', 'leaf_green.png'],
  'diamond-pearl': ['diamond.webp', 'pearl.webp'],
  platinum: ['platinum.webp'],
  'heartgold-soulsilver': ['heart_gold.webp', 'soul_silver.webp'],
  'black-white': ['black.webp', 'white.webp'],
  'black-2-white-2': ['black-2.webp', 'white-2.webp'],
  'x-y': ['x.webp', 'y.webp'],
  'omega-ruby-alpha-sapphire': ['omega_ruby.png', 'alpha_sapphire.png'],
  'sun-moon': ['sun.webp', 'moon.webp'],
  'ultra-sun-ultra-moon': ['ultra-sun.webp', 'ultra-moon.webp'],
  'lets-go-pikachu-lets-go-eevee': ['lets_go_pikachu.jpg', 'lets_go_eevee.jpg'],
  'sword-shield': ['sword.webp', 'shield.webp'],
  'brilliant-diamond-and-shining-pearl': [
    'brilliant-diamond.webp',
    'shining-pearl.webp',
  ],
  'legends-arceus': ['legends_arceus.webp'],
  'scarlet-violet': ['scarlet.webp', 'violet.webp'],
  'legends-z-a': ['legends_za.webp'],
};
