export const bgVariants: Record<string, string> = {
  normal: 'bg-normal/10 dark:bg-normal/20',
  fire: 'bg-fire/10 dark:bg-fire/20',
  water: 'bg-water/10 dark:bg-water/20',
  grass: 'bg-grass/10 dark:bg-grass/20',
  electric: 'bg-electric/10 dark:bg-electric/20',
  ice: 'bg-ice/10 dark:bg-ice/20',
  fighting: 'bg-fighting/10 dark:bg-fighting/20',
  poison: 'bg-poison/10 dark:bg-poison/20',
  ground: 'bg-ground/10 dark:bg-ground/20',
  flying: 'bg-flying/10 dark:bg-flying/20',
  psychic: 'bg-psychic/10 dark:bg-psychic/20',
  bug: 'bg-bug/10 dark:bg-bug/20',
  rock: 'bg-rock/10 dark:bg-rock/20',
  ghost: 'bg-ghost/10 dark:bg-ghost/20',
  dragon: 'bg-dragon/10 dark:bg-dragon/20',
  dark: 'bg-dark/10 dark:bg-dark/20',
  steel: 'bg-steel/10 dark:bg-steel/20',
  fairy: 'bg-fairy/10 dark:bg-fairy/20',
  unknown: 'bg-unknown/10 dark:bg-unknown/20',
};
